INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        1,
        'GB/T 706-2016 热轧型钢',
        '10',
        100,
        68,
        4.5,
        7.6,
        6.5,
        3.3,
        14.33,
        11.3,
        0.43,
        245,
        33,
        4.14,
        1.52,
        49,
        9.72
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        2,
        'GB/T 706-2016 热轧型钢',
        '12',
        120,
        74,
        5,
        8.4,
        7,
        3.5,
        17.8,
        14,
        0.49,
        436,
        46.9,
        4.95,
        1.62,
        72.7,
        12.7
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        3,
        'GB/T 706-2016 热轧型钢',
        '12.6',
        126,
        74,
        5,
        8.4,
        7,
        3.5,
        18.1,
        14.2,
        0.51,
        488,
        46.9,
        5.2,
        1.61,
        77.5,
        12.7
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        4,
        'GB/T 706-2016 热轧型钢',
        '14',
        140,
        80,
        5.5,
        9.1,
        7.5,
        3.8,
        21.5,
        16.9,
        0.55,
        712,
        64.4,
        5.76,
        1.73,
        102,
        16.1
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        5,
        'GB/T 706-2016 热轧型钢',
        '16',
        160,
        88,
        6,
        9.9,
        8,
        4,
        26.11,
        20.5,
        0.62,
        1130,
        93.1,
        6.58,
        1.89,
        141,
        21.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        6,
        'GB/T 706-2016 热轧型钢',
        '18',
        180,
        94,
        6.5,
        10.7,
        8.5,
        4.3,
        30.74,
        24.1,
        0.68,
        1660,
        122,
        7.36,
        2,
        185,
        26
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        7,
        'GB/T 706-2016 热轧型钢',
        '20a',
        200,
        100,
        7,
        11.4,
        9,
        4.5,
        35.55,
        27.9,
        0.74,
        2370,
        158,
        8.15,
        2.12,
        237,
        31.5
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        8,
        'GB/T 706-2016 热轧型钢',
        '20b',
        200,
        102,
        9,
        11.4,
        9,
        4.5,
        39.55,
        31.1,
        0.75,
        2500,
        169,
        7.96,
        2.06,
        250,
        33.1
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        9,
        'GB/T 706-2016 热轧型钢',
        '22a',
        220,
        110,
        7.5,
        12.3,
        9.5,
        4.8,
        42.1,
        33.1,
        0.82,
        3400,
        225,
        8.99,
        2.31,
        309,
        40.9
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        10,
        'GB/T 706-2016 热轧型钢',
        '22b',
        220,
        112,
        9.5,
        12.3,
        9.5,
        4.8,
        46.5,
        36.5,
        0.82,
        3570,
        239,
        8.78,
        2.27,
        325,
        42.7
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        11,
        'GB/T 706-2016 热轧型钢',
        '24a',
        240,
        116,
        8,
        13,
        10,
        5,
        47.71,
        37.5,
        0.88,
        4570,
        280,
        9.77,
        2.42,
        381,
        48.4
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        12,
        'GB/T 706-2016 热轧型钢',
        '24b',
        240,
        118,
        10,
        13,
        10,
        5,
        52.51,
        41.2,
        0.88,
        4800,
        297,
        9.57,
        2.38,
        400,
        50.4
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        13,
        'GB/T 706-2016 热轧型钢',
        '25a',
        250,
        116,
        8,
        13,
        10,
        5,
        48.51,
        38.1,
        0.9,
        5020,
        280,
        10.2,
        2.4,
        402,
        48.3
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        14,
        'GB/T 706-2016 热轧型钢',
        '25b',
        250,
        118,
        10,
        13,
        10,
        5,
        53.51,
        42,
        0.9,
        5280,
        309,
        9.94,
        2.4,
        423,
        52.4
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        15,
        'GB/T 706-2016 热轧型钢',
        '27a',
        270,
        122,
        8.5,
        13.7,
        10.5,
        5.3,
        54.52,
        42.8,
        0.96,
        6550,
        345,
        10.9,
        2.51,
        485,
        56.6
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        16,
        'GB/T 706-2016 热轧型钢',
        '27b',
        270,
        124,
        10.5,
        13.7,
        10.5,
        5.3,
        59.92,
        47,
        0.96,
        6870,
        366,
        10.7,
        2.47,
        509,
        58.9
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        17,
        'GB/T 706-2016 热轧型钢',
        '28a',
        280,
        122,
        8.5,
        13.7,
        10.5,
        5.3,
        55.37,
        43.5,
        0.98,
        7110,
        345,
        11.3,
        2.5,
        508,
        56.6
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        18,
        'GB/T 706-2016 热轧型钢',
        '28b',
        280,
        124,
        10.5,
        13.7,
        10.5,
        5.3,
        60.97,
        47.9,
        0.98,
        7480,
        379,
        11.1,
        2.49,
        534,
        61.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        19,
        'GB/T 706-2016 热轧型钢',
        '30a',
        300,
        126,
        9,
        14.4,
        11,
        5.5,
        61.22,
        48.1,
        1.03,
        8950,
        400,
        12.1,
        2.55,
        597,
        63.5
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        20,
        'GB/T 706-2016 热轧型钢',
        '30b',
        300,
        128,
        11,
        14.4,
        11,
        5.5,
        67.22,
        52.8,
        1.04,
        9400,
        422,
        11.8,
        2.5,
        627,
        65.9
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        21,
        'GB/T 706-2016 热轧型钢',
        '30c',
        300,
        130,
        13,
        14.4,
        11,
        5.5,
        73.22,
        57.5,
        1.04,
        9850,
        445,
        11.6,
        2.46,
        657,
        68.5
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        22,
        'GB/T 706-2016 热轧型钢',
        '32a',
        320,
        130,
        9.5,
        15,
        11.5,
        5.8,
        67.12,
        52.7,
        1.08,
        11100,
        460,
        12.8,
        2.62,
        692,
        70.8
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        23,
        'GB/T 706-2016 热轧型钢',
        '32b',
        320,
        132,
        11.5,
        15,
        11.5,
        5.8,
        73.52,
        57.7,
        1.09,
        11600,
        502,
        12.6,
        2.61,
        726,
        76
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        24,
        'GB/T 706-2016 热轧型钢',
        '32c',
        320,
        134,
        13.5,
        15,
        11.5,
        5.8,
        79.92,
        62.7,
        1.09,
        12200,
        544,
        12.3,
        2.61,
        760,
        81.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        25,
        'GB/T 706-2016 热轧型钢',
        '36a',
        360,
        136,
        10,
        15.8,
        12,
        6,
        76.44,
        60,
        1.19,
        15800,
        552,
        14.4,
        2.69,
        875,
        81.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        26,
        'GB/T 706-2016 热轧型钢',
        '36b',
        360,
        138,
        12,
        15.8,
        12,
        6,
        83.64,
        65.7,
        1.19,
        16500,
        582,
        14.1,
        2.64,
        919,
        84.3
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        27,
        'GB/T 706-2016 热轧型钢',
        '36c',
        360,
        140,
        14,
        15.8,
        12,
        6,
        90.84,
        71.3,
        1.19,
        17300,
        612,
        13.8,
        2.6,
        962,
        87.4
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        28,
        'GB/T 706-2016 热轧型钢',
        '40a',
        400,
        142,
        10.5,
        16.5,
        12.5,
        6.3,
        86.07,
        67.6,
        1.29,
        21700,
        660,
        15.9,
        2.77,
        1090,
        93.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        29,
        'GB/T 706-2016 热轧型钢',
        '40b',
        400,
        144,
        12.5,
        16.5,
        12.5,
        6.3,
        94.07,
        73.8,
        1.29,
        22800,
        692,
        15.6,
        2.71,
        1140,
        96.2
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        30,
        'GB/T 706-2016 热轧型钢',
        '40c',
        400,
        146,
        14.5,
        16.5,
        12.5,
        6.3,
        102.1,
        80.1,
        1.29,
        23900,
        727,
        15.2,
        2.65,
        1190,
        99.6
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        31,
        'GB/T 706-2016 热轧型钢',
        '45a',
        450,
        150,
        11.5,
        18,
        13.5,
        6.8,
        102.4,
        80.4,
        1.41,
        32200,
        855,
        17.7,
        2.89,
        1430,
        114
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        32,
        'GB/T 706-2016 热轧型钢',
        '45b',
        450,
        152,
        13.5,
        18,
        13.5,
        6.8,
        111.4,
        87.4,
        1.42,
        33800,
        894,
        17.4,
        2.84,
        1500,
        118
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        33,
        'GB/T 706-2016 热轧型钢',
        '45c',
        450,
        154,
        15.5,
        18,
        13.5,
        6.8,
        120.4,
        94.5,
        1.42,
        35300,
        938,
        17.1,
        2.79,
        1570,
        122
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        34,
        'GB/T 706-2016 热轧型钢',
        '50a',
        500,
        158,
        12,
        20,
        14,
        7,
        119.2,
        93.6,
        1.54,
        46500,
        1120,
        19.7,
        3.07,
        1860,
        142
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        35,
        'GB/T 706-2016 热轧型钢',
        '50b',
        500,
        160,
        14,
        20,
        14,
        7,
        129.2,
        101,
        1.54,
        48600,
        1170,
        19.4,
        3.01,
        1940,
        146
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        36,
        'GB/T 706-2016 热轧型钢',
        '50c',
        500,
        162,
        16,
        20,
        14,
        7,
        139.2,
        109,
        1.55,
        50600,
        1220,
        19,
        2.96,
        2080,
        151
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        37,
        'GB/T 706-2016 热轧型钢',
        '55a',
        550,
        166,
        12.5,
        21,
        14.5,
        7.3,
        134.1,
        105,
        1.67,
        62900,
        1370,
        21.6,
        3.19,
        2290,
        164
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        38,
        'GB/T 706-2016 热轧型钢',
        '55b',
        550,
        168,
        14.5,
        21,
        14.5,
        7.3,
        145.1,
        114,
        1.67,
        65600,
        1420,
        21.2,
        3.14,
        2390,
        170
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        39,
        'GB/T 706-2016 热轧型钢',
        '55c',
        550,
        170,
        16.5,
        21,
        14.5,
        7.3,
        156.1,
        123,
        1.68,
        68400,
        1480,
        20.9,
        3.08,
        2490,
        175
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        40,
        'GB/T 706-2016 热轧型钢',
        '56a',
        560,
        166,
        12.5,
        21,
        14.5,
        7.3,
        135.4,
        106,
        1.69,
        65600,
        1370,
        22,
        3.18,
        2340,
        165
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        41,
        'GB/T 706-2016 热轧型钢',
        '56b',
        560,
        168,
        14.5,
        21,
        14.5,
        7.3,
        146.6,
        115,
        1.69,
        68500,
        1490,
        21.6,
        3.16,
        2450,
        174
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        42,
        'GB/T 706-2016 热轧型钢',
        '56c',
        560,
        170,
        16.5,
        21,
        14.5,
        7.3,
        157.8,
        124,
        1.7,
        71400,
        1560,
        21.3,
        3.16,
        2550,
        183
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        43,
        'GB/T 706-2016 热轧型钢',
        '63a',
        630,
        176,
        13,
        22,
        15,
        7.5,
        154.6,
        121,
        1.86,
        93900,
        1700,
        24.5,
        3.31,
        2980,
        193
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        44,
        'GB/T 706-2016 热轧型钢',
        '63b',
        630,
        178,
        15,
        22,
        15,
        7.5,
        167.2,
        131,
        1.87,
        98100,
        1810,
        24.2,
        3.29,
        3160,
        204
    );

INSERT INTO
    section_steel_contour.i (
        i_id,
        i_standard,
        i_specification,
        i_h,
        i_b,
        i_d,
        i_t,
        i_r,
        i_r1,
        i_sc,
        i_weight,
        i_se,
        i_ix,
        i_iy,
        i_rx,
        i_ry,
        i_wx,
        i_wy
    )
VALUES (
        45,
        'GB/T 706-2016 热轧型钢',
        '63c',
        630,
        180,
        17,
        22,
        15,
        7.5,
        179.8,
        141,
        1.87,
        102000,
        1920,
        23.8,
        3.27,
        3300,
        214
    );