INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        1,
        'GB/T 706-2016 热轧型钢',
        '50x50',
        50,
        50,
        5,
        7,
        8,
        5.92,
        4.65,
        0.193,
        11.8,
        7.39,
        1.41,
        1.11,
        3.18,
        2.95,
        1.28,
        '100x50'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        2,
        'GB/T 706-2016 热轧型钢',
        '62.5x60',
        62.5,
        60,
        6,
        8,
        8,
        8.34,
        6.55,
        0.238,
        27.5,
        14.6,
        1.81,
        1.32,
        5.96,
        4.85,
        1.64,
        '125x60'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        3,
        'GB/T 706-2016 热轧型钢',
        '75x75',
        75,
        75,
        5,
        7,
        8,
        8.92,
        7,
        0.293,
        42.6,
        24.7,
        2.18,
        1.66,
        7.46,
        6.59,
        1.79,
        '150x75'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        4,
        'GB/T 706-2016 热轧型钢',
        '87.5x90',
        85.5,
        89,
        4,
        6,
        8,
        8.79,
        6.9,
        0.342,
        53.7,
        35.3,
        2.47,
        2,
        8.02,
        7.94,
        1.86,
        '175x90'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        5,
        'GB/T 706-2016 热轧型钢',
        '87.5x90',
        87.5,
        90,
        5,
        8,
        8,
        11.44,
        8.98,
        0.348,
        70.6,
        48.7,
        2.48,
        2.06,
        10.4,
        10.8,
        1.93,
        '175x90'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        6,
        'GB/T 706-2016 热轧型钢',
        '100x100',
        99,
        99,
        4.5,
        7,
        8,
        11.34,
        8.9,
        0.389,
        93.5,
        56.7,
        2.87,
        2.23,
        12.1,
        11.5,
        2.17,
        '200x100'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        7,
        'GB/T 706-2016 热轧型钢',
        '100x100',
        100,
        100,
        5.5,
        8,
        8,
        13.33,
        10.5,
        0.393,
        114,
        66.9,
        2.92,
        2.23,
        14.8,
        13.4,
        2.31,
        '200x100'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        8,
        'GB/T 706-2016 热轧型钢',
        '125x125',
        124,
        124,
        5,
        8,
        8,
        15.99,
        12.6,
        0.489,
        207,
        127,
        3.59,
        2.82,
        21.3,
        20.5,
        2.66,
        '250x125'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        9,
        'GB/T 706-2016 热轧型钢',
        '125x125',
        125,
        125,
        6,
        9,
        8,
        18.48,
        14.5,
        0.493,
        248,
        147,
        3.66,
        2.81,
        25.6,
        23.5,
        2.81,
        '250x125'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        10,
        'GB/T 706-2016 热轧型钢',
        '150x150',
        149,
        149,
        5.5,
        8,
        13,
        20.4,
        16,
        0.585,
        393,
        221,
        4.39,
        3.29,
        33.8,
        29.7,
        3.26,
        '300x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        11,
        'GB/T 706-2016 热轧型钢',
        '150x150',
        150,
        150,
        6.5,
        9,
        13,
        23.39,
        18.4,
        0.589,
        464,
        254,
        4.45,
        3.29,
        40,
        33.8,
        3.41,
        '300x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        12,
        'GB/T 706-2016 热轧型钢',
        '175x175',
        173,
        174,
        6,
        9,
        13,
        26.22,
        20.6,
        0.683,
        679,
        396,
        5.08,
        3.88,
        50,
        45.5,
        3.72,
        '350x175'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        13,
        'GB/T 706-2016 热轧型钢',
        '175x175',
        175,
        175,
        7,
        11,
        13,
        31.45,
        24.7,
        0.689,
        814,
        492,
        5.08,
        3.95,
        59.3,
        56.2,
        3.76,
        '350x175'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        14,
        'GB/T 706-2016 热轧型钢',
        '200x200',
        198,
        199,
        7,
        11,
        13,
        35.7,
        28,
        0.783,
        1190,
        723,
        5.77,
        4.5,
        76.4,
        72.7,
        4.2,
        '400x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        15,
        'GB/T 706-2016 热轧型钢',
        '200x200',
        200,
        200,
        8,
        13,
        13,
        41.68,
        32.7,
        0.789,
        1390,
        868,
        5.78,
        4.56,
        88.6,
        86.8,
        4.26,
        '400x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        16,
        'GB/T 706-2016 热轧型钢',
        '225x150',
        223,
        150,
        7,
        12,
        13,
        33.49,
        26.3,
        0.735,
        1570,
        338,
        6.84,
        3.17,
        93.7,
        45.1,
        5.54,
        '450x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        17,
        'GB/T 706-2016 热轧型钢',
        '225x150',
        225,
        151,
        8,
        14,
        13,
        38.74,
        30.4,
        0.741,
        1830,
        403,
        6.87,
        3.22,
        108,
        53.4,
        5.62,
        '450x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        18,
        'GB/T 706-2016 热轧型钢',
        '225x200',
        223,
        199,
        8,
        12,
        13,
        41.48,
        32.6,
        0.833,
        1870,
        789,
        6.71,
        4.36,
        109,
        79.3,
        5.15,
        '450x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        19,
        'GB/T 706-2016 热轧型钢',
        '225x200',
        225,
        200,
        9,
        14,
        13,
        47.71,
        37.5,
        0.839,
        2150,
        935,
        6.71,
        4.42,
        124,
        93.5,
        5.19,
        '450x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        20,
        'GB/T 706-2016 热轧型钢',
        '237.5x150',
        235,
        150,
        7,
        13,
        13,
        35.76,
        28.1,
        0.759,
        1850,
        367,
        7.18,
        3.2,
        104,
        48.9,
        7.5,
        '475x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        21,
        'GB/T 706-2016 热轧型钢',
        '237.5x150',
        237.5,
        151.5,
        8.5,
        15.5,
        13,
        43.07,
        33.8,
        0.767,
        2270,
        451,
        7.25,
        3.23,
        128,
        59.5,
        7.57,
        '475x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        22,
        'GB/T 706-2016 热轧型钢',
        '237.5x150',
        241,
        153.5,
        10.5,
        19,
        13,
        53.2,
        41.8,
        0.778,
        2860,
        575,
        7.33,
        3.28,
        160,
        75,
        7.67,
        '475x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        23,
        'GB/T 706-2016 热轧型钢',
        '250x150',
        246,
        150,
        7,
        12,
        13,
        35.1,
        27.6,
        0.781,
        2060,
        339,
        7.66,
        3.1,
        113,
        45.1,
        6.36,
        '500x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        24,
        'GB/T 706-2016 热轧型钢',
        '250x150',
        250,
        152,
        9,
        16,
        13,
        46.1,
        36.2,
        0.793,
        2750,
        470,
        7.71,
        3.19,
        149,
        61.9,
        6.53,
        '500x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        25,
        'GB/T 706-2016 热轧型钢',
        '250x150',
        252,
        153,
        10,
        18,
        13,
        51.66,
        40.6,
        0.799,
        3100,
        540,
        7.74,
        3.23,
        167,
        70.5,
        6.62,
        '500x150'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        26,
        'GB/T 706-2016 热轧型钢',
        '250x200',
        248,
        199,
        9,
        14,
        13,
        49.64,
        39,
        0.883,
        2820,
        921,
        7.54,
        4.3,
        150,
        92.6,
        5.97,
        '500x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        27,
        'GB/T 706-2016 热轧型钢',
        '250x200',
        250,
        200,
        10,
        16,
        13,
        56.12,
        44.1,
        0.889,
        3200,
        1070,
        7.54,
        4.36,
        169,
        107,
        6.03,
        '500x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        28,
        'GB/T 706-2016 热轧型钢',
        '250x200',
        253,
        201,
        11,
        19,
        13,
        64.65,
        50.8,
        0.897,
        3660,
        1290,
        7.52,
        4.46,
        189,
        128,
        6,
        '500x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        29,
        'GB/T 706-2016 热轧型钢',
        '275x200',
        273,
        199,
        9,
        14,
        13,
        51.89,
        40.7,
        0.933,
        3690,
        921,
        8.43,
        4.21,
        180,
        92.6,
        6.85,
        '550x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        30,
        'GB/T 706-2016 热轧型钢',
        '275x200',
        275,
        200,
        10,
        16,
        13,
        58.62,
        46,
        0.939,
        4180,
        1070,
        8.44,
        4.27,
        203,
        107,
        6.89,
        '550x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        31,
        'GB/T 706-2016 热轧型钢',
        '300x200',
        298,
        199,
        10,
        15,
        13,
        58.87,
        46.2,
        0.983,
        5150,
        988,
        9.35,
        4.09,
        235,
        99.3,
        7.92,
        '600x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        32,
        'GB/T 706-2016 热轧型钢',
        '300x200',
        300,
        200,
        11,
        17,
        13,
        65.85,
        51.7,
        0.989,
        5770,
        1140,
        9.35,
        4.15,
        262,
        114,
        7.95,
        '600x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        33,
        'GB/T 706-2016 热轧型钢',
        '300x200',
        303,
        201,
        12,
        20,
        13,
        74.88,
        58.8,
        0.997,
        6530,
        1360,
        9.33,
        4.25,
        291,
        135,
        7.88,
        '600x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        34,
        'GB/T 706-2016 热轧型钢',
        '312.5x200',
        312.5,
        198.5,
        13.5,
        17.5,
        13,
        75.28,
        59.1,
        1.01,
        7460,
        1150,
        9.95,
        3.9,
        338,
        116,
        9.15,
        '625x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        35,
        'GB/T 706-2016 热轧型钢',
        '312.5x200',
        315,
        200,
        15,
        20,
        13,
        84.97,
        66.7,
        1.02,
        8470,
        1340,
        9.98,
        3.97,
        380,
        134,
        9.21,
        '625x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        36,
        'GB/T 706-2016 热轧型钢',
        '312.5x200',
        319,
        202,
        17,
        24,
        13,
        99.35,
        78,
        1.03,
        9960,
        1160,
        10,
        4.08,
        440,
        165,
        9.26,
        '625x200'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        37,
        'GB/T 706-2016 热轧型钢',
        '325x300',
        323,
        299,
        12,
        18,
        18,
        91.81,
        72.1,
        1.23,
        8570,
        4020,
        9.66,
        6.61,
        344,
        269,
        7.36,
        '650x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        38,
        'GB/T 706-2016 热轧型钢',
        '325x300',
        325,
        300,
        13,
        20,
        18,
        101,
        79.3,
        1.23,
        9430,
        4510,
        9.66,
        6.67,
        376,
        300,
        7.4,
        '650x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        39,
        'GB/T 706-2016 热轧型钢',
        '325x300',
        327,
        301,
        14,
        22,
        18,
        110.3,
        86.59,
        1.24,
        10300,
        5010,
        9.66,
        6.73,
        408,
        333,
        7.45,
        '650x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        40,
        'GB/T 706-2016 热轧型钢',
        '350x300',
        346,
        300,
        13,
        20,
        18,
        103.8,
        81.5,
        1.28,
        11300,
        4510,
        10.4,
        6.59,
        424,
        301,
        8.09,
        '700x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        41,
        'GB/T 706-2016 热轧型钢',
        '350x300',
        350,
        300,
        13,
        24,
        18,
        115.8,
        90.9,
        1.28,
        12000,
        5410,
        10.2,
        6.83,
        438,
        361,
        7.63,
        '700x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        42,
        'GB/T 706-2016 热轧型钢',
        '400x300',
        396,
        300,
        14,
        22,
        18,
        119.8,
        94,
        1.38,
        17600,
        4960,
        12.1,
        6.43,
        592,
        331,
        9.78,
        '800x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        43,
        'GB/T 706-2016 热轧型钢',
        '400x300',
        400,
        300,
        14,
        26,
        18,
        131.8,
        103,
        1.38,
        18700,
        5860,
        11.9,
        6.66,
        610,
        391,
        9.27,
        '800x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        44,
        'GB/T 706-2016 热轧型钢',
        '450x300',
        445,
        299,
        15,
        23,
        18,
        133.5,
        105,
        1.47,
        25900,
        5140,
        13.9,
        6.2,
        789,
        344,
        11.7,
        '900x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        45,
        'GB/T 706-2016 热轧型钢',
        '450x300',
        450,
        300,
        16,
        28,
        18,
        152.9,
        120,
        1.48,
        29100,
        3206,
        13.8,
        6.42,
        865,
        421,
        11.4,
        '900x300'
    );

INSERT INTO
    section_steel_contour.h_tn (
        tn_id,
        tn_standard,
        tn_specification,
        tn_h,
        tn_b,
        tn_t1,
        tn_t2,
        tn_r,
        tn_sc,
        tn_weight,
        tn_se,
        tn_ix,
        tn_iy,
        tn_rx,
        tn_ry,
        tn_wx,
        tn_wy,
        tn_cx,
        tn_specification_h
    )
VALUES (
        46,
        'GB/T 706-2016 热轧型钢',
        '450x300',
        456,
        302,
        18,
        34,
        18,
        180,
        141,
        1.5,
        34100,
        8307,
        13.8,
        6.59,
        997,
        518,
        11.3,
        '900x300'
    );