INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        1,
        'GB/T 706-2016 热轧型钢',
        '75x100',
        74,
        100,
        6,
        9,
        8,
        13.17,
        10.3,
        0.341,
        51.7,
        75.2,
        1.98,
        2.38,
        8.84,
        15,
        1.56,
        '150x100'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        2,
        'GB/T 706-2016 热轧型钢',
        '100x150',
        97,
        150,
        6,
        9,
        8,
        19.05,
        15,
        0.487,
        124,
        253,
        2.55,
        3.64,
        15.8,
        33.8,
        1.8,
        '200x150'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        3,
        'GB/T 706-2016 热轧型钢',
        '125x175',
        122,
        175,
        7,
        11,
        13,
        27.74,
        21.8,
        0.583,
        288,
        492,
        3.22,
        4.21,
        29.1,
        56.2,
        2.28,
        '250x175'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        4,
        'GB/T 706-2016 热轧型钢',
        '150x200',
        147,
        200,
        8,
        12,
        13,
        35.52,
        27.9,
        0.683,
        571,
        801,
        4,
        4.74,
        48.2,
        80.1,
        2.85,
        '300x200'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        5,
        'GB/T 706-2016 热轧型钢',
        '150x200',
        149,
        201,
        9,
        14,
        13,
        41.01,
        32.2,
        0.689,
        661,
        949,
        4.01,
        4.8,
        55.2,
        94.4,
        2.92,
        '300x200'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        6,
        'GB/T 706-2016 热轧型钢',
        '175x250',
        170,
        250,
        9,
        14,
        13,
        49.76,
        39.1,
        0.829,
        1020,
        1820,
        4.51,
        6.05,
        73.2,
        146,
        3.11,
        '350x250'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        7,
        'GB/T 706-2016 热轧型钢',
        '200x300',
        195,
        300,
        10,
        16,
        13,
        66.62,
        52.3,
        0.979,
        1730,
        3600,
        5.09,
        7.35,
        108,
        240,
        3.43,
        '400x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        8,
        'GB/T 706-2016 热轧型钢',
        '225x300',
        220,
        300,
        11,
        18,
        13,
        76.94,
        60.4,
        1.03,
        2680,
        4050,
        5.89,
        7.25,
        150,
        270,
        4.09,
        '450x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        9,
        'GB/T 706-2016 热轧型钢',
        '250x300',
        241,
        300,
        11,
        15,
        13,
        70.58,
        55.4,
        1.07,
        3400,
        3380,
        6.93,
        6.91,
        178,
        225,
        5,
        '500x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        10,
        'GB/T 706-2016 热轧型钢',
        '250x300',
        244,
        300,
        11,
        18,
        13,
        79.58,
        62.5,
        1.08,
        3610,
        4050,
        6.73,
        7.13,
        184,
        270,
        4.72,
        '500x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        11,
        'GB/T 706-2016 热轧型钢',
        '275x300',
        272,
        300,
        11,
        15,
        13,
        73.99,
        58.1,
        1.13,
        4790,
        3380,
        8.04,
        6.75,
        225,
        225,
        5.96,
        '550x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        12,
        'GB/T 706-2016 热轧型钢',
        '275x300',
        275,
        300,
        11,
        18,
        13,
        82.99,
        65.2,
        1.14,
        5090,
        4050,
        7.82,
        6.98,
        232,
        270,
        5.59,
        '550x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        13,
        'GB/T 706-2016 热轧型钢',
        '300x300',
        291,
        300,
        12,
        17,
        13,
        84.6,
        66.4,
        1.17,
        6320,
        3830,
        8.64,
        6.72,
        280,
        255,
        6.51,
        '600x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        14,
        'GB/T 706-2016 热轧型钢',
        '300x300',
        294,
        300,
        12,
        20,
        13,
        93.6,
        73.5,
        1.18,
        6680,
        4500,
        8.44,
        6.93,
        288,
        300,
        6.17,
        '600x300'
    );

INSERT INTO
    section_steel_contour.h_tm (
        tm_id,
        tm_standard,
        tm_specification,
        tm_h,
        tm_b,
        tm_t1,
        tm_t2,
        tm_r,
        tm_sc,
        tm_weight,
        tm_se,
        tm_ix,
        tm_iy,
        tm_rx,
        tm_ry,
        tm_wx,
        tm_wy,
        tm_cx,
        tm_specification_h
    )
VALUES (
        15,
        'GB/T 706-2016 热轧型钢',
        '300x300',
        297,
        302,
        14,
        23,
        13,
        108.5,
        85.2,
        1.19,
        7890,
        5290,
        8.52,
        6.97,
        339,
        350,
        6.41,
        '600x300'
    );