INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        1,
        'GB/T 706-2016 热轧型钢',
        '5',
        50,
        37,
        4.5,
        7,
        7,
        3.5,
        6.925,
        5.44,
        0.226,
        26,
        8.3,
        20.9,
        1.94,
        1.1,
        10.4,
        3.55,
        1.35
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        2,
        'GB/T 706-2016 热轧型钢',
        '6.3',
        63,
        40,
        4.8,
        7.5,
        7.5,
        3.8,
        8.446,
        6.63,
        0.262,
        50.8,
        11.9,
        28.4,
        2.45,
        1.19,
        16.1,
        4.5,
        1.36
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        3,
        'GB/T 706-2016 热轧型钢',
        '6.5',
        65,
        40,
        4.3,
        7.5,
        7.5,
        3.8,
        8.292,
        6.51,
        0.267,
        55.2,
        12,
        28.3,
        2.54,
        1.19,
        17,
        4.59,
        1.38
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        4,
        'GB/T 706-2016 热轧型钢',
        '8',
        80,
        43,
        5,
        8,
        8,
        4,
        10.24,
        8.04,
        0.307,
        101,
        16.6,
        37.4,
        3.15,
        1.27,
        25.3,
        5.79,
        1.43
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        5,
        'GB/T 706-2016 热轧型钢',
        '10',
        100,
        48,
        5.3,
        8.5,
        8.5,
        4.2,
        12.74,
        10,
        0.365,
        198,
        25.6,
        54.9,
        3.95,
        1.41,
        39.7,
        7.8,
        1.52
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        6,
        'GB/T 706-2016 热轧型钢',
        '12',
        120,
        53,
        5.5,
        9,
        9,
        4.5,
        15.36,
        12.1,
        0.423,
        346,
        37.4,
        77.7,
        4.75,
        1.56,
        57.7,
        10.2,
        1.62
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        7,
        'GB/T 706-2016 热轧型钢',
        '12.6',
        126,
        53,
        5.5,
        9,
        9,
        4.5,
        15.69,
        12.3,
        0.435,
        391,
        38,
        77.1,
        4.95,
        1.57,
        62.1,
        10.2,
        1.59
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        8,
        'GB/T 706-2016 热轧型钢',
        '14a',
        140,
        58,
        6,
        9.5,
        9.5,
        4.8,
        18.51,
        14.5,
        0.48,
        564,
        53.2,
        107,
        5.52,
        1.7,
        80.5,
        13,
        1.71
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        9,
        'GB/T 706-2016 热轧型钢',
        '14b',
        140,
        60,
        8,
        9.5,
        9.5,
        4.8,
        21.31,
        16.7,
        0.484,
        609,
        61.1,
        121,
        5.35,
        1.69,
        87.1,
        14.1,
        1.67
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        10,
        'GB/T 706-2016 热轧型钢',
        '16a',
        160,
        63,
        6.5,
        10,
        10,
        5,
        21.95,
        17.2,
        0.538,
        866,
        73.3,
        144,
        6.28,
        1.83,
        108,
        16.3,
        1.8
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        11,
        'GB/T 706-2016 热轧型钢',
        '16b',
        160,
        65,
        8.5,
        10,
        10,
        5,
        25.15,
        19.8,
        0.542,
        935,
        83.4,
        161,
        6.1,
        1.82,
        117,
        17.6,
        1.75
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        12,
        'GB/T 706-2016 热轧型钢',
        '18a',
        180,
        68,
        7,
        10.5,
        10.5,
        5.2,
        25.69,
        20.2,
        0.596,
        1270,
        98.6,
        190,
        7.04,
        1.96,
        141,
        20,
        1.88
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        13,
        'GB/T 706-2016 热轧型钢',
        '18b',
        180,
        70,
        9,
        10.5,
        10.5,
        5.2,
        29.29,
        23,
        0.6,
        1370,
        111,
        210,
        6.84,
        1.95,
        152,
        21.5,
        1.84
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        14,
        'GB/T 706-2016 热轧型钢',
        '20a',
        200,
        73,
        7,
        11,
        11,
        5.5,
        28.83,
        22.6,
        0.654,
        1780,
        128,
        244,
        7.86,
        2.11,
        178,
        24.2,
        2.01
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        15,
        'GB/T 706-2016 热轧型钢',
        '20b',
        200,
        75,
        9,
        11,
        11,
        5.5,
        32.83,
        25.8,
        0.658,
        1910,
        144,
        268,
        7.64,
        2.09,
        191,
        25.9,
        1.95
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        16,
        'GB/T 706-2016 热轧型钢',
        '22a',
        220,
        77,
        7,
        11.5,
        11.5,
        5.8,
        31.83,
        25,
        0.709,
        2390,
        158,
        298,
        8.67,
        2.23,
        218,
        28.2,
        2.1
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        17,
        'GB/T 706-2016 热轧型钢',
        '22b',
        220,
        79,
        9,
        11.5,
        11.5,
        5.8,
        36.23,
        28.5,
        0.713,
        2570,
        176,
        326,
        8.42,
        2.21,
        234,
        30.1,
        2.03
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        18,
        'GB/T 706-2016 热轧型钢',
        '24a',
        240,
        78,
        7,
        12,
        12,
        6,
        34.21,
        26.9,
        0.752,
        3050,
        174,
        325,
        9.45,
        2.25,
        254,
        30.5,
        2.1
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        19,
        'GB/T 706-2016 热轧型钢',
        '24b',
        240,
        80,
        9,
        12,
        12,
        6,
        39.01,
        30.6,
        0.756,
        3280,
        194,
        355,
        9.17,
        2.23,
        274,
        32.5,
        2.03
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        20,
        'GB/T 706-2016 热轧型钢',
        '24c',
        240,
        82,
        11,
        12,
        12,
        6,
        43.81,
        34.4,
        0.76,
        3510,
        213,
        388,
        8.96,
        2.21,
        293,
        34.4,
        2
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        21,
        'GB/T 706-2016 热轧型钢',
        '25a',
        250,
        78,
        7,
        12,
        12,
        6,
        34.91,
        27.4,
        0.722,
        3370,
        176,
        322,
        9.82,
        2.24,
        270,
        30.6,
        2.07
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        22,
        'GB/T 706-2016 热轧型钢',
        '25b',
        250,
        80,
        9,
        12,
        12,
        6,
        39.91,
        31.3,
        0.776,
        3530,
        196,
        353,
        9.41,
        2.22,
        282,
        32.7,
        1.98
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        23,
        'GB/T 706-2016 热轧型钢',
        '25c',
        250,
        82,
        11,
        12,
        12,
        6,
        44.91,
        35.3,
        0.78,
        3690,
        218,
        384,
        9.07,
        2.21,
        295,
        35.9,
        1.92
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        24,
        'GB/T 706-2016 热轧型钢',
        '27a',
        270,
        82,
        7.5,
        12.5,
        12.5,
        6.2,
        39.27,
        30.8,
        0.826,
        4360,
        216,
        393,
        10.5,
        2.34,
        323,
        35.5,
        2.13
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        25,
        'GB/T 706-2016 热轧型钢',
        '27b',
        270,
        84,
        9.5,
        12.5,
        12.5,
        6.2,
        44.67,
        35.1,
        0.83,
        4690,
        239,
        428,
        10.3,
        2.31,
        347,
        37.7,
        2.06
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        26,
        'GB/T 706-2016 热轧型钢',
        '27c',
        270,
        86,
        11.5,
        12.5,
        12.5,
        6.2,
        50.07,
        39.3,
        0.834,
        5020,
        261,
        467,
        10.1,
        2.28,
        372,
        39.8,
        2.03
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        27,
        'GB/T 706-2016 热轧型钢',
        '28a',
        280,
        82,
        7.5,
        12.5,
        12.5,
        6.2,
        40.02,
        31.4,
        0.846,
        4760,
        218,
        388,
        10.9,
        2.33,
        340,
        35.7,
        2.1
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        28,
        'GB/T 706-2016 热轧型钢',
        '28b',
        280,
        84,
        9.5,
        12.5,
        12.5,
        6.2,
        45.62,
        35.8,
        0.85,
        5130,
        242,
        428,
        10.6,
        2.3,
        366,
        37.9,
        2.02
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        29,
        'GB/T 706-2016 热轧型钢',
        '28c',
        280,
        86,
        11.5,
        12.5,
        12.5,
        6.2,
        51.22,
        40.2,
        0.854,
        5500,
        268,
        463,
        10.4,
        2.29,
        393,
        40.3,
        1.95
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        30,
        'GB/T 706-2016 热轧型钢',
        '30a',
        300,
        85,
        7.5,
        13.5,
        13.5,
        6.8,
        43.89,
        34.5,
        0.897,
        6050,
        260,
        467,
        11.7,
        2.43,
        403,
        41.1,
        2.17
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        31,
        'GB/T 706-2016 热轧型钢',
        '30b',
        300,
        87,
        9.5,
        13.5,
        13.5,
        6.8,
        49.89,
        39.2,
        0.901,
        6500,
        289,
        515,
        11.4,
        2.41,
        433,
        44,
        2.13
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        32,
        'GB/T 706-2016 热轧型钢',
        '30c',
        300,
        89,
        11.5,
        13.5,
        13.5,
        6.8,
        55.89,
        43.9,
        0.905,
        6950,
        316,
        560,
        11.2,
        2.38,
        463,
        46.4,
        2.09
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        33,
        'GB/T 706-2016 热轧型钢',
        '32a',
        320,
        88,
        8,
        14,
        14,
        7,
        48.5,
        38.1,
        0.947,
        7600,
        305,
        552,
        12.5,
        2.5,
        475,
        46.5,
        2.24
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        34,
        'GB/T 706-2016 热轧型钢',
        '32b',
        320,
        90,
        10,
        14,
        14,
        7,
        54.9,
        43.1,
        0.951,
        8140,
        336,
        593,
        12.2,
        2.47,
        509,
        49.2,
        2.16
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        35,
        'GB/T 706-2016 热轧型钢',
        '32c',
        320,
        92,
        12,
        14,
        14,
        7,
        61.3,
        48.1,
        0.955,
        8690,
        374,
        643,
        11.9,
        2.47,
        543,
        52.6,
        2.09
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        36,
        'GB/T 706-2016 热轧型钢',
        '36a',
        360,
        96,
        9,
        16,
        16,
        8,
        60.89,
        47.8,
        1.053,
        11900,
        455,
        818,
        14,
        2.73,
        660,
        63.5,
        2.44
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        37,
        'GB/T 706-2016 热轧型钢',
        '36b',
        360,
        98,
        11,
        16,
        16,
        8,
        68.09,
        53.5,
        1.057,
        12700,
        497,
        880,
        13.6,
        2.7,
        703,
        66.9,
        2.37
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        38,
        'GB/T 706-2016 热轧型钢',
        '36c',
        360,
        100,
        13,
        16,
        16,
        8,
        75.29,
        59.1,
        1.061,
        13400,
        536,
        948,
        13.4,
        2.67,
        746,
        70,
        2.34
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        39,
        'GB/T 706-2016 热轧型钢',
        '40a',
        400,
        100,
        10.5,
        18,
        18,
        9,
        75.04,
        58.9,
        1.144,
        17600,
        592,
        1070,
        15.3,
        2.81,
        879,
        78.8,
        2.49
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        40,
        'GB/T 706-2016 热轧型钢',
        '40b',
        400,
        102,
        12.5,
        18,
        18,
        9,
        83.04,
        65.2,
        1.148,
        18600,
        640,
        1140,
        15,
        2.78,
        932,
        82.5,
        2.44
    );

INSERT INTO
    section_steel_contour.c (
        c_id,
        c_standard,
        c_specification,
        c_h,
        c_b,
        c_d,
        c_t,
        c_r,
        c_r1,
        c_sc,
        c_weight,
        c_se,
        c_ix,
        c_iy,
        c_iy1,
        c_rx,
        c_ry,
        c_wx,
        c_wy,
        c_z0
    )
VALUES (
        41,
        'GB/T 706-2016 热轧型钢',
        '40c',
        400,
        104,
        14.5,
        18,
        18,
        9,
        91.04,
        71.5,
        1.152,
        19700,
        688,
        1220,
        14.7,
        2.75,
        986,
        86.2,
        2.42
    );